import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AppImages {
  static const logo = 'assets/images/logo.png';
  static const graduate = 'assets/images/graduated.png';
  static const profile = 'assets/images/profile.png';
  static const founder = 'assets/images/founder.png';
  static const team = 'assets/images/team.png';

}

class AppColor {
  static const bg = const Color(0xffE5E5E5);
  static const nblue = const Color(0xff47D7F6);
  static const purple = const Color(0xffBF7EFF);
}

List<String> courseList = [
  'Medicine',
  'Pharmacy',
  'Engineering',
  'Acccounting',
  'Chemistry',
  'Physics',
  'Political Scince',
  'Geography',
  'Economics',
  'Fine Arts',
  'Music'
];
List<String> industryList = [
  "B2B",
  "B2C",
  "C2C",
  "D2C",
  "E2P",
  "E2E",
  "P2P",
  "Fintech",
  "EdTech",
  "Proptech",
  "Travel Tech",
  "Real estate ",
  "AI/ ML",
  "Renewable energy",
  "Block chain",
  "Crypto",
  "Gaming",
  "AR/ VR",
  "ERP/CRM",
  "Audio tech",
  "Cosmetics",
  "Biotechnology",
  "Clean Tech ",
  "E-commerce",
  "Gig Economy ",
  "IOT",
  "HR Tech",
  "Messaging",
  "Social Impact",
  "Hospitality",
  "SAAS",
  "PAAS",
  "Logistics",
  "Health",
  "Gov Tech",
  "Future of Work",
  "Community",
  "Cloud applications ",
  "Insurance",
  "Legal Tech",
  "Agriculture",
  "Food and Beverage",
  "Entertainment",
  "Nonprofit",
  "ITC/ Voice Search ",
  "NFT",
  "Fashion",
  "Automotive",
  "Aerospace",
  "Marketing",
  "Infrastructure",
  "Construction",
  "Social networking ",
  "Crowdfunding",
  "Cannabis/ CBD",
  "Technology",
  "Consumer",
  "Mobile apps",
  "Matchmaking",
  "Dating/ Romance ",
  "Self improvement ",
  "Coaching",
  "Fitness/ activity tracking",
];

List<String> locationList = [];

List<String> goalsList = [
  "Looking for exclusive deal flow",
  "Looking to mentor entrepreneurs",
  "Looking for a Co-founder",
  "Looking to connect with investors",
  "Looking for team members",
  "Looking for early employees",
  "Looking for co-investors",
  "Looking for interns",
  "Looking for Advisors/ Mentors",
  "Looking for Advisees / Mentees",
  "Looking for domain experts ",
  "Looking for beta users / feedback",
  "Looking to discover people in my niche",
  "Looking to discover people with similar interests",
  "Looking to discover new products",
  "Looking to join new communities",
  "Looking for advice",
  "Looking for entrepreneurial inspiration",
  "Looking for job opportunities",
  "Looking for gig work",
  "Keeping all of my options open",
];

List<String> experineceList = [
  "None, I'm looking to gain experience",
  "Less than one year",
  "1 year",
  "2 years",
  "3 years ",
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  "8 years",
  "9 years ",
  "10+ years ",
  "Exited a company",
  "Exited 2 companies",
  "Serial Entrepreneur",
];

List<String> pronounsList = [
    "Any pronouns",
    "He/Him",
    "Co/Co",
    "Dhey/Dhem",
    "Elle/Elles",
    "Elle/he",
    "Elle/they",
    "En/En",
    "Ey/En",
    "Ey/em",
    "Fey/fem",
    "He/Him",
    "Hir/Hirs",
    "MySelf",
    "Per/per",
    "She/her",
    "She/he",
    "They/he",
    "They/she",
    "They/she/he",
    "They/them",
    "Vae/vem",
    "Ve/ver",
    "Ve/vis",
    "Xe/him",
    "Xe/she",
    "Xe/he/she",
    "Xe/he/they",
    "Xe/she/they",
    "Xe/they",
    "Xe/xem ",
    "Xie/hir",
    "Yo/yo",
    "Ze/zie",
    "Ze/zi",
  ];